include Makefile.inc

C_SRCS += \
src/sql/sql.c

OBJS += \
src/sql/sql.o

C_DEPS += \
src/sql/sql.d

# Each subdirectory must supply rules for building sources it contributes
%.o: %.c
	@echo 'CC:  $<'
	$(CC) $(CFLAGS) -c -o $@ $<	

