CC = gcc
CFLAGS = -I/usr/include/postgresql -fsigned-char -O0 -ggdb -Wall 
LD = gcc
LDFLAGS = -L/usr/lib -L/usr/lib/postgresql/9.1/lib
AR = ar
ARFLAGS = 
RANLIB = ranlib
RM = rm
ECHO = echo

SHELL = /bin/sh

.SILENT:

