include Makefile.inc

C_SRCS += \
src/rtc/a10i2c.c \
src/rtc/rtc4162.c \
src/rtc/rtc.c 

OBJS += \
src/rtc/a10i2c.o \
src/rtc/rtc4162.o \
src/rtc/rtc.o 

C_DEPS += \
src/rtc/a10i2c.d \
src/rtc/rtc4162.d \
src/rtc/rtc.d 

# Each subdirectory must supply rules for building sources it contributes
%.o: %.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler $(CC) $(CFLAGS) -c  -o $@ $<'
	$(CC) $(CFLAGS) -c  -o $@ $<
	@echo 'Finished building: $<'
	@echo ' '  
	

