include Makefile.inc

C_SRCS += \
src/devicehandler.c \
src/liegw.c \
src/settings.c \
src/log.c

OBJS += \
src/devicehandler.o \
src/liegw.o \
src/settings.o \
src/log.o

C_DEPS += \
src/devicehandler.d \
src/liegw.d \
src/settings.d \
src/log.d

# Each subdirectory must supply rules for building sources it contributes
%.o: %.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	$(CC) $(CFLAGS) -c  -o $@ $<
	@echo 'Finished building: $<'
	@echo ' '  
	

