include Makefile.inc

C_SRCS += \
src/coap/coapserver.c \
src/coap/mycoap.c \

OBJS += \
src/coap/coapserver.o \
src/coap/mycoap.o \

C_DEPS += \
src/coap/coapserver.d \
src/coap/mycoap.d \

%.o: %.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	$(CC) $(CFLAGS) -c -o $@ $<
	@echo 'Finished building: $<'
	@echo ' '

